export default {
    msg: {
        owner: "Fitur hanya bisa diakses oleh owner!",
        group: "Fitur hanya bisa digunakan didalam group!",
        private: "Fitur hanya bisa digunakan di private chat!",
        admin: "Fitur hanya bisa diakses oleh admin group!",
        botAdmin: "Bot bukan admin, Tidak bisa menggunakan fitur ini!",
        bot: "Anda tidak bisa menggunakan fitur ini.",
        media: "Reply media...",
        query: "Masukan Querynya.",
        error: "Sepertinya ada masalah saat pemrosesan.",
        quoted: "Reply pesannya...",
        wait: "Tunggu...",
        urlInvalid: "Url Invalid",
        notFound: "Hasil tidak ditemukan!",
        premium: "Fitur ini hanya bisa digunakan oleh user Premium!",
        limit: "Maaf limit anda habis, limit akan di reset setiap jam 12 malam.",
        format: (type) => `Hanya menerima format ${type}!`,
    },
};
